/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.socialsketch.tool.ui;

/**
 *
 * @author Dimitry Kireyenkov <dimitry@languagekings.com>
 */
public class Consolepane extends javax.swing.JPanel {

    /**
     * Creates new form Consolepane
     */
    public Consolepane() {
        initComponents();
    }
    
    /**
     * Just adds line to console (with line end).
     * 
     * @param line 
     */
    public void addLine(String line){
        txtaMainConsole.append(line + "\n");
        // TODO: add scrolling to bottom.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtaMainConsole = new javax.swing.JTextArea();

        txtaMainConsole.setBackground(new java.awt.Color(0, 0, 0));
        txtaMainConsole.setColumns(20);
        txtaMainConsole.setForeground(new java.awt.Color(51, 255, 0));
        txtaMainConsole.setRows(5);
        jScrollPane1.setViewportView(txtaMainConsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaMainConsole;
    // End of variables declaration//GEN-END:variables
}
